.github/workflows/test.yaml
Makefile
README.md

Add GitHub workflow for running the AIO distribution e2e tests.

Add e2e testing workflow

---

.github/workflows/push.yaml
.gitignore
Makefile
main.cue
main_tool.cue

Push manifests to `oci://ghcr.io/stefanprodan/manifests/flux-aio`

Publish OCI artifacts to GHCR

---

Brewfile
Makefile
README.md
distribution/deployment.cue
distribution/flux-auto.cue
distribution/flux.cue
main.cue
main_tool.cue

Implement `cue automate` to configure Flux self-update.

Configure Flux self-update with OCI artifacts

---

cue.mod/gen/k8s.io/api/core/v1/types_go_gen.cue
cue.mod/gen/k8s.io/api/resource/v1alpha1/types_go_gen.cue
distribution/crds.cue
main.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.0.0-rc.1

Update Flux to v2.0.0-rc.1

---

distribution/crds.cue
distribution/deployment.cue
main.cue

Add `priorityClassName: "system-cluster-critical"` to match upstream.

Update Flux to v2.0.0-rc.2

---

modules/flux-aio/templates/config.cue
modules/flux-aio/templates/resourcequota.cue

Comply with GKE requirements for `system-cluster-critical` priority class.

Add resource quota for critical pods

---

modules/flux-aio/values.cue

Changelog https://github.com/fluxcd/flux2/releases/tag/v2.0.0-rc.5

Update Flux to v2.0.0-rc.5

---

README.md
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.0.1

Update Flux to v2.0.1

---

README.md
modules/flux-aio/templates/crds.cue
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.1.0

Update Flux to v2.1.0

---

.github/workflows/push.yaml
Makefile
bundles/flux-aio.cue
modules/flux-aio/templates/config.cue
modules/flux-aio/timoni.cue

Changes:
- Push flux-aio module signed with Cosign keyless (GitHub OIDC)
- Set min Kubernetes version for the flux-aio module
- Inject module URL and version from runtime in the flux-aio Bundle

Migrate module to Timoni v0.13.0

---

.github/workflows/test.yaml

Use Timoni Bundle Runtime API in e2e tests.

Use Timoni bundle in e2e tests

---

README.md
modules/flux-aio/values.cue

Changelog https://github.com/fluxcd/flux2/releases/tag/v2.1.1

Update Flux to v2.1.1

---

README.md
modules/flux-aio/README.md
modules/flux-aio/templates/config.cue
modules/flux-aio/templates/env.cue
modules/flux-aio/templates/helm-controller.cue
modules/flux-aio/templates/kustomize-controller.cue
modules/flux-aio/templates/notification-controller.cue
modules/flux-aio/templates/source-controller.cue

Allow setting HTTP and HTTPS proxies to the Flux controllers containers.

Add HTTP/S proxy setting

---

README.md

If the Git token is not found in env vars, error out `values.git.token: incomplete value`.

Make Git token required for private repos

---

README.md
modules/flux-aio/debug_tool.cue
modules/flux-aio/debug_values.cue
modules/flux-aio/timoni.ignore
modules/flux-aio/values.cue

Add debug values for CUE eval
```shell
cue -t debug -t name=flux -t namespace=flux-system -t mv=2.0.0 -t kv=1.28.0 eval -c -e timoni.instance.objects.deployment
```

Add CUE debug tool to flux-aio module

---

README.md
modules/flux-aio/templates/config.cue
modules/flux-aio/templates/rbac.cue
modules/flux-aio/values.cue

Changelog https://github.com/fluxcd/flux2/releases/tag/v2.1.2

Update Flux to v2.1.2

---

modules/flux-helm-release/README.md
modules/flux-helm-release/debug_values.cue
modules/flux-helm-release/templates/config.cue
modules/flux-helm-release/templates/helmrepository.cue

Allow pulling from from private Helm repos

Add auth options to flux-helm-release module

---

README.md
modules/flux-git-sync/README.md
modules/flux-git-sync/templates/config.cue
modules/flux-git-sync/templates/gitrepository.cue

Allow configuring CA for self-hosted Git servers

---

modules/flux-aio/debug_values.cue
modules/flux-aio/templates/config.cue

Evict Flux from an unreachable node after 5m

---

modules/flux-aio/debug_values.cue
modules/flux-aio/templates/config.cue
modules/flux-aio/templates/deployment.cue
modules/flux-aio/templates/env.cue
modules/flux-aio/templates/pvc.cue
modules/flux-aio/timoni.cue
modules/flux-git-sync/templates/gitrepository.cue
modules/flux-git-sync/templates/kustomization.cue
modules/flux-git-sync/timoni.cue
modules/flux-helm-release/templates/config.cue
modules/flux-helm-release/templates/helmrelease.cue
modules/flux-helm-release/templates/helmrepository.cue
modules/flux-helm-release/timoni.cue
modules/flux-tenant/templates/config.cue
modules/flux-tenant/timoni.cue

Fix tolerations type

---

README.md
modules/flux-aio/templates/crds.cue
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/v2.2.1

Update Flux to v2.2.1

---

test/cluster/kind.yaml

Use latest Kubernetes release for e2e tests.

Update Kubernetes to v1.29

---

README.md

Document how to sync with a bootstrap repository layout.

Add docs for bootstrap repo sync

---

modules/flux-aio/templates/config.cue
modules/flux-aio/templates/deployment.cue
modules/flux-aio/templates/env.cue
modules/flux-aio/templates/helm-controller.cue
modules/flux-aio/templates/kustomize-controller.cue
modules/flux-aio/templates/namespace.cue
modules/flux-aio/templates/notification-controller.cue
modules/flux-aio/templates/pvc.cue
modules/flux-aio/templates/rbac.cue
modules/flux-aio/templates/resourcequota.cue
modules/flux-aio/templates/serviceaccount.cue
modules/flux-aio/templates/services.cue
modules/flux-aio/templates/source-controller.cue
modules/flux-git-sync/templates/config.cue
modules/flux-git-sync/templates/gitrepository.cue
modules/flux-git-sync/templates/kustomization.cue
modules/flux-helm-release/templates/config.cue
modules/flux-helm-release/templates/helmrelease.cue
modules/flux-helm-release/templates/helmrepository.cue
modules/flux-tenant/templates/config.cue
modules/flux-tenant/templates/namespace.cue
modules/flux-tenant/templates/rbac.cue
modules/flux-tenant/templates/resourcequota.cue
modules/flux-tenant/templates/serviceaccount.cue

Use `#config` definition instead of a private field to pass values internally.

Refactor internal config handling

---

modules/flux-aio/debug_values.cue
modules/flux-aio/templates/serviceaccount.cue

Add workload identity to debug values to validated the mapping fix.
Fix: #68

Fix workload identity

---

README.md
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.2.3

Update Flux to v2.2.3

---

.github/workflows/e2e.yaml
.github/workflows/test.yaml

Run vet on PRs from forks and e2e tests on all branches.

Move e2e tests to dedicated workflow

---

modules/flux-aio/cue.mod/module.cue
modules/flux-aio/templates/config.cue
modules/flux-git-sync/cue.mod/module.cue
modules/flux-git-sync/values.cue
modules/flux-helm-release/cue.mod/module.cue
modules/flux-helm-release/values.cue
modules/flux-oci-sync/cue.mod/module.cue
modules/flux-oci-sync/values.cue
modules/flux-tenant/cue.mod/module.cue
modules/flux-tenant/values.cue

Adapt modules to CUE v0.9 breaking changes

Set CUE language version

---

modules/flux-aio/templates/env.cue

Use `list.Concat` for CUE 0.11 and Timoni 0.23

---

README.md
modules/flux-aio/values.cue

changelog: https://github.com/fluxcd/flux2/releases/tag/v2.6.2

Update Flux to v2.6.2

---

README.md
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.6.3

Update Flux to v2.6.3

---

README.md
modules/flux-aio/values.cue

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.6.4

Update Flux to v2.6.4
