- distribution/deployment.cue
In this weeks episode of echo office hours I was attempting to use flux-aio as a clusterresourceset. It worked great except that the resulting deployment wasn't configured to use hostNetwork and didn't tolerate the node not ready taint.
This change adds those so that flux-aio can be used in a cluster where there is not yet a deployed cni.
Signed-off-by: Duffie Cooley <dcooley@isovalent.com>
> Adding hostnet and tolerations.

- README.md
- distribution/flux.cue
- distribution/helm-controller.cue
- distribution/kustomize-controller.cue
- distribution/notification-controller.cue
- distribution/service.cue
- distribution/source-controller.cue
The Flux pod binds to the following ports on the host network:
- `9292` notification-controller webhook receiver endpoint
- `9690` notification-controller events receiver endpoint
- `9790` source-controller storage endpoint
- `9791-9799` metrics, liveness and readiness endpoints
> Update host ports mapping

- .github/workflows/test.yaml
- test/cni/cilium.yaml
- test/cni/kind.yaml
This PR adds an e2e test to verify that Flux can deploy a CNI plugin.
Test workflow:
- Install Kubernetes Kind without a CNI plugin
- Install Flux on the cluster
- Test that the Flux pod starts without a CNI plugin
- Install Cilium using a Flux HelmRelease
- Wait for Flux to deploy Cilium
- Test that CoreDNS has become healthy
Followup: #8
> Add e2e test for CNI with Cilium

- .github/workflows/test.yaml
- Makefile
- distribution/deployment.cue
- distribution/flux-auto.cue
- distribution/flux.cue
- distribution/helm-controller.cue
- distribution/kustomize-controller.cue
- distribution/notification-controller.cue
- main.cue
- main_tool.cue
- test/cni/cilium.yaml
Add a `securityProfile` field to the distribution which accepts one of these values:  `restricted` and `privileged`.  To enable the [Flux multi-tenancy lockdown](https://fluxcd.io/flux/installation/#multi-tenancy-lockdown), set `securityProfile: "restricted"`.
> Implement security profile

- modules/flux-aio/README.md
- modules/flux-aio/templates/config.cue
- modules/flux-aio/templates/helm-controller.cue
- modules/flux-aio/templates/kustomize-controller.cue
- modules/flux-aio/templates/source-controller.cue
New config options:
- `reconcile: concurrent` sets the maximum number of parallel reconciliations per controller
- `reconcile: requeue` sets the interval in seconds at which failing dependencies are reevaluated
New defaults:
- disable leader election to reduce Kubernetes API calls (AIO prevents multiple pods from running in parallel so leader election is not needed)
- enable Helm index caching for source-controller (reduces memory usage by 50% when using large Helm HTTP repos)
> Allow fine-tuning of Flux reconcilers

- modules/flux-aio/templates/config.cue
- modules/flux-aio/templates/deployment.cue
Prevent running more then one Flux pod per Kubernetes node.
> Add pod anti-affinity to prevent host ports conflicts

- .github/workflows/test.yaml
- modules/flux-git-sync/README.md
- modules/flux-git-sync/debug_values.cue
- modules/flux-git-sync/templates/config.cue
- modules/flux-git-sync/templates/kustomization.cue
Changes:
- Add `serviceAccountName` and `targetNamespace` to `flux-git-sync` options
- Vet modules in CI using the debug values
> Add impersonation options to git-sync module 

- modules/flux-git-sync/README.md
- modules/flux-git-sync/templates/config.cue
- modules/flux-git-sync/templates/kustomization.cue
Extent the flux-git-sync with [post build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution) capabilities.
> Allow configuring post build variable substitution

- README.md
- test/cluster/kind.yaml
Bump Kubernetes to v1.28.0 for e2e tests.
> Update Kubernetes to v1.28

- .github/workflows/push.yaml
- Makefile
- README.md
Change the versioning of Flux AIO distribution and all its modules to the following format:
`<flux version>-<distribution release number>`, e.g. `2.2.2-0`.
> Adopt semver for distribution releases

- modules/flux-helm-release/README.md
- modules/flux-helm-release/templates/config.cue
- modules/flux-helm-release/templates/helmrepository.cue
Add `repository: provider` option for configuring ODIC-based auth in the `flux-helm-release` module.
Add `repository: insecure` option for allow Flux to pull charts from an insecure (HTTP) OCI registry server.
> Add Cloud OIDC provider support for OCI Helm repositories

- modules/flux-aio/templates/config.cue
I noticed this when I tried to use this a moment ago:
```
5:34PM ERR build failed for flux:
timoni.instance.config.imagePullSecrets.0: undefined field: LocalObjectReference:
./templates/config.cue:97:32
timoni.instance.objects.deployment.spec.template.spec.imagePullSecrets.0: undefined field: LocalObjectReference:
./templates/config.cue:97:32
```
> fix: image pull secrets definition

- modules/flux-git-sync/README.md
- modules/flux-git-sync/templates/config.cue
- modules/flux-git-sync/templates/kustomization.cue
- modules/flux-helm-release/README.md
- modules/flux-helm-release/templates/config.cue
- modules/flux-helm-release/templates/helmrelease.cue
- modules/flux-oci-sync/README.md
- modules/flux-oci-sync/templates/config.cue
- modules/flux-oci-sync/templates/kustomization.cue
This adds a `dependsOn` clause to each of the modules:
- flux-git-sync
- flux-helm-release
- flux-oci-sync
> feat(modules): add depends on to the generated kustomize and helm releases

- modules/flux-aio/templates/kustomize-controller.cue
Enable transferring ownership of server-side apply managed fields from Timoni to Flux.
> Transfer SSA field ownership to Flux

- modules/flux-helm-release/README.md
- modules/flux-helm-release/debug_values.cue
- modules/flux-helm-release/templates/config.cue
- modules/flux-helm-release/templates/helmrelease.cue
Allow enabling Helm testing and drift detection for Helm releases. Also set the metadata labels and annotations for the generated HelmChart object.
> Add drift detection and test options to flux-helm-release module

- README.md
- modules/flux-aio/debug_values.cue
- modules/flux-aio/templates/crds.cue
- modules/flux-aio/templates/env.cue
- modules/flux-aio/values.cue
xref: https://github.com/fluxcd/flux2/issues/4712
> Update Flux to v2.3.0

- modules/flux-aio/README.md
- modules/flux-aio/templates/config.cue
- modules/flux-aio/templates/deployment.cue
Add a config option `compatibility: "openshift"` for making Flux AIO run on OpenShift.
Tested on OpenShift 4.15.0-okd.
> Add OpenShift compatibility

- bundles/flux-tenants.cue
- modules/flux-helm-release/templates/config.cue
- modules/flux-helm-release/templates/helmrelease.cue
- modules/flux-helm-release/templates/helmrepository.cue
- modules/flux-helm-release/templates/ocirepository.cue
When the repository URL points to an OCI registry, the `flux-helm-release` module generates an `OCIRepository` instead of a `HelmRepository/HelmChart`.
> Generate `OCIRepository` with `flux-helm-release` module

- README.md
- modules/flux-aio/README.md
- modules/flux-aio/debug_values.cue
- modules/flux-aio/templates/config.cue
- modules/flux-aio/templates/namespace.cue
Introduce a new config option in the `flux-aio` module called `podSecurityProfile` for setting the `pod-security.kubernetes.io` labels on the namespace where Flux is deployed. 
Add a note in the readme for Talos to set the pod security to `privileged`.
Fix: #97
> Allow setting the pod security labels on the Flux namespace

- modules/flux-helm-release/README.md
- modules/flux-helm-release/templates/config.cue
- modules/flux-helm-release/templates/helmrelease.cue
We would like to be able to target non-existing namespaces in the HelmReleases of our timoni bundles.
This changes adds a sync.createNamespace optional value to activate this option.
> add sync.createNamespace value to flux-helm-release module
